from __future__ import annotations

import io
import os
import time

import torch
from PIL import Image
from google.genai import types

import sys
_custom_nodes_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _custom_nodes_dir not in sys.path:
    sys.path.insert(0, _custom_nodes_dir)

from shared.gemini_client import (
    create_gemini_client, tensor_to_pil, TEXT_MODELS,
)

# ── Prompts ──────────────────────────────────────────────────────────────────

IDENTITY_PRESERVATION_PROMPT = """You are evaluating multiple generated images from an Image-to-Image AI model.
Image 1 is the reference input image showing a specific person.
The subsequent images are Candidates 1 to N, which are variations generated by the AI based on Image 1.

Your task:
1. Eliminate candidates that fail to preserve the facial identity, skin tone, or distinct physical features of the person in Image 1.
2. Eliminate candidates with obvious AI artifacts (extra fingers, unnatural blending, weird anatomy, blurred details).
3. From the remaining acceptable candidates, select the SINGLE BEST candidate that looks the most natural, photorealistic, and faithful to the reference person.

If ALL candidates fail one of the checks above and are unacceptable, your `best_candidate` must be 0.
Otherwise, return the integer number of the best candidate (1 to N).

You must respond ONLY with a valid JSON object matching this schema:
{
  "best_candidate": integer (0 if all fail, or 1 to N for the winner),
  "reason": "Brief explanation of why this specific candidate won, or why they all failed."
}"""

def _pil_to_bytes(img: Image.Image) -> bytes:
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


class OmniIdentityGate:
    """Binary PASS/FAIL gate with batch filtering for Image-to-Image.

    1. Receives a batch of generated images from ImageToImage.
    2. Validates images sequentially against a reference image.
    3. The first image that PASSES is returned immediately.
    4. If all images FAIL, returns the first image with passed=False (fallback).
    """

    CATEGORY = "Omni"
    RETURN_TYPES = ("IMAGE", "BOOLEAN", "STRING")
    RETURN_NAMES = ("image", "passed", "report")
    FUNCTION = "gate"
    OUTPUT_NODE = False

    DESCRIPTION = (
        "Validates generative variations against a reference image via Gemini Vision. "
        "Outputs the candidate that best preserves the identity and lacks AI artifacts. "
        "If all fail, returns first image as fallback."
    )

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "gemini_config": ("GEMINI_CONFIG",),
                "model": (TEXT_MODELS, {"default": "gemini-2.5-flash"}),
                "reference_image": ("IMAGE",),
                "generated_images": ("IMAGE",),
            },
            "optional": {
                "skip_trigger": ("STRING", {"forceInput": True, "tooltip": "Status message to evaluate."})
            }
        }

    def gate(self, gemini_config, reference_image, generated_images, model="gemini-2.5-flash", skip_trigger=""):
        if skip_trigger and skip_trigger.strip().upper().startswith("FAIL"):
            print(f"[OmniIdentityGate] 🛑 Upstream failure detected. Skipping validation and propagating FAIL.")
            first_candidate = generated_images[0].unsqueeze(0)
            return (first_candidate, False, skip_trigger)

        client = create_gemini_client(gemini_config)

        def _get_first_image_bytes(t):
            t_single = t[0].unsqueeze(0) if t.dim() == 4 else t
            return _pil_to_bytes(tensor_to_pil(t_single))

        ref_bytes = _get_first_image_bytes(reference_image)
        batch_size = generated_images.shape[0]
        
        contents = [
            "Image 1 — Reference Person:",
            types.Part.from_bytes(data=ref_bytes, mime_type="image/png"),
        ]

        for i in range(batch_size):
            candidate_tensor = generated_images[i].unsqueeze(0)
            candidate_bytes = _pil_to_bytes(tensor_to_pil(candidate_tensor))
            contents.extend([
                f"Candidate {i + 1}:",
                types.Part.from_bytes(data=candidate_bytes, mime_type="image/png")
            ])
            
        contents.append(IDENTITY_PRESERVATION_PROMPT)

        print(f"[OmniIdentityGate] Evaluating {batch_size} candidate(s) against reference...")
        
        result_json = self._call_gemini_json(client, model, contents)
        best_id = result_json.get("best_candidate", 0)
        reason = result_json.get("reason", "No reason provided")

        if not isinstance(best_id, int):
            try:
                best_id = int(best_id)
            except ValueError:
                print(f"[OmniIdentityGate] ⚠ Invalid best_candidate parsed '{best_id}'. Defaulting to 1.")
                best_id = 1
                
        if best_id <= 0 or best_id > batch_size:
            print(f"[OmniIdentityGate] ❌ ALL FAILED. ({reason})")
            print(f"[OmniIdentityGate] ⚠ Utilizing best-effort fallback (Returning Candidate 1). Emitting FAIL trigger.")
            first_candidate = generated_images[0].unsqueeze(0)
            return (first_candidate, False, f"FAIL: {reason}")
            
        winner_index = best_id - 1
        print(f"[OmniIdentityGate] ✅ WINNER: Candidate {best_id}/{batch_size} — {reason}")
        winner_tensor = generated_images[winner_index].unsqueeze(0)
        return (winner_tensor, True, f"✅ PASS (Candidate {best_id}): {reason}")

    def _call_gemini_json(self, client, model, contents) -> dict:
        import json
        config = {
            "response_modalities": ["TEXT"],
            "temperature": 0.1,
            "response_mime_type": "application/json",
        }
        for attempt in range(2):
            try:
                response = client.models.generate_content(model=model, contents=contents, config=config)
                if response and hasattr(response, "text") and response.text:
                    return json.loads(response.text.strip())
                raise ValueError("Empty API response")
            except Exception as e:
                if attempt == 0:
                    print(f"[OmniIdentityGate] ⚠ Validation API error: {e}. Retrying in 5s…")
                    time.sleep(5)
                else:
                    print(f"[OmniIdentityGate] ⚠ Retry failed.")
                    return {"best_candidate": 1, "reason": f"API Error: {str(e)[:80]}"}
                    
        return {"best_candidate": 1, "reason": "API Error: Unknown"}

    @classmethod
    def IS_CHANGED(cls, **kwargs):
        import time
        return time.time()
